// Generated by CoffeeScript 1.9.3
(function() {
  var User;

  User = (function() {
    function User(_client, data) {
      var k;
      this._client = _client;
      if (data == null) {
        data = {};
      }
      for (k in data || {}) {
        this[k] = data[k];
      }
    }

    return User;

  })();

  module.exports = User;

}).call(this);
